# Generated by Django 3.2.5 on 2023-01-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disa', models.CharField(blank=True, max_length=2, null=True, verbose_name='cod_disa')),
                ('desc_disa', models.CharField(blank=True, max_length=40, null=True, verbose_name='desc_disa')),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_provincia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rpt_metales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_estab', models.CharField(blank=True, max_length=9, null=True, verbose_name='cod_estab')),
                ('anio', models.CharField(blank=True, max_length=4, null=True, verbose_name='anio')),
                ('mes', models.CharField(blank=True, max_length=4, null=True, verbose_name='mes')),
                ('fichafam', models.CharField(blank=True, max_length=4, null=True, verbose_name='fichafam')),
                ('sexo', models.CharField(blank=True, max_length=4, null=True, verbose_name='sexo')),
                ('establec', models.CharField(blank=True, max_length=4, null=True, verbose_name='establec')),
                ('servicio', models.CharField(blank=True, max_length=4, null=True, verbose_name='servicio')),
                ('id_cita', models.CharField(blank=True, max_length=40, null=True, verbose_name='id_cita')),
                ('fecha_atendido', models.CharField(blank=True, max_length=40, null=True, verbose_name='fecha_atendido')),
                ('num_doc', models.CharField(blank=True, max_length=40, null=True, verbose_name='num_doc')),
                ('cod_item', models.CharField(blank=True, max_length=40, null=True, verbose_name='cod_item')),
                ('valor_lab', models.CharField(blank=True, max_length=40, null=True, verbose_name='valor_lab')),
                ('edad', models.CharField(blank=True, max_length=40, null=True, verbose_name='edad')),
                ('ubigeo', models.CharField(blank=True, max_length=40, null=True, verbose_name='ubigeo')),
                ('codpsal', models.CharField(blank=True, max_length=40, null=True, verbose_name='codpsal')),
                ('cod_prof', models.CharField(blank=True, max_length=40, null=True, verbose_name='cod_prof')),
                ('tipo_estab', models.CharField(blank=True, max_length=40, null=True, verbose_name='tipo_estab')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_reporte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_red', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cod_red', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('cod_enlace', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('disa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disas', to='atendidos.disa')),
            ],
        ),
        migrations.CreateModel(
            name='Microred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_microred', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_mic', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('cod_red', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('cod_enlace_mr', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('cod_enlace_r', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='atendidos.red')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_unico', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cod_enlace_mr', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('id_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atendidos.red')),
                ('microred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microredes', to='atendidos.microred')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('id_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atendidos.provincia')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='atendidos.provincia')),
            ],
        ),
    ]
