# Generated by Django 3.2.16 on 2023-01-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nominal_trama_nuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Cita', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id_Cita')),
                ('Anio', models.CharField(blank=True, max_length=4, null=True, verbose_name='Anio')),
                ('Mes', models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes')),
                ('Dia', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dia')),
                ('Fecha_Atencion', models.DateField(blank=True, max_length=20, null=True, verbose_name='Fecha_Atencion')),
                ('Lote', models.CharField(blank=True, max_length=3, null=True, verbose_name='Lote')),
                ('Num_Pag', models.IntegerField(blank=True, null=True, verbose_name='Num_Pag')),
                ('Num_Reg', models.IntegerField(blank=True, null=True, verbose_name='Num_Reg')),
                ('Id_Ups', models.CharField(blank=True, max_length=6, null=True, verbose_name='Id_Ups')),
                ('Id_Establecimiento', models.IntegerField(blank=True, null=True, verbose_name='Id_Establecimiento')),
                ('Id_Paciente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id_Paciente')),
                ('Id_Personal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id_Personal')),
                ('Id_Registrador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id_Registrador')),
                ('Id_Financiador', models.CharField(blank=True, max_length=2, null=True, verbose_name='Id_Financiador')),
                ('Id_Condicion_Establecimiento', models.CharField(blank=True, max_length=1, null=True, verbose_name='Id_Condicion_Establecimiento')),
                ('Id_Condicion_Servicio', models.CharField(blank=True, max_length=1, null=True, verbose_name='Id_Condicion_Servicio')),
                ('Edad_Reg', models.IntegerField(blank=True, null=True, verbose_name='Edad_Reg')),
                ('Tipo_Edad', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo_Edad')),
                ('Anio_Actual_Paciente', models.IntegerField(blank=True, null=True, verbose_name='Anio_Actual_Paciente')),
                ('Mes_Actual_Paciente', models.IntegerField(blank=True, null=True, verbose_name='Mes_Actual_Paciente')),
                ('Dia_Actual_Paciente', models.IntegerField(blank=True, null=True, verbose_name='Dia_Actual_Paciente')),
                ('Id_Turno', models.CharField(blank=True, max_length=1, null=True, verbose_name='Id_Turno')),
                ('Codigo_Item', models.CharField(blank=True, max_length=15, null=True, verbose_name='Codigo_Item')),
                ('Tipo_Diagnostico', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo_Diagnostico')),
                ('Valor_Lab', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor_Lab')),
                ('Id_Correlativo_Item', models.IntegerField(blank=True, null=True, verbose_name='Id_Correlativo_Item')),
                ('Id_Correlativo_Lab', models.IntegerField(blank=True, null=True, verbose_name='Id_Correlativo_Lab')),
                ('Peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso')),
                ('Talla', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Talla')),
                ('Hemoglobina', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hemoglobina')),
                ('Perimetro_Abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perimetro_Abdominal')),
                ('Perimetro_Cefalico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perimetro_Cefalico')),
                ('Id_Otra_Condicion', models.IntegerField(blank=True, null=True, verbose_name='Id_Otra_Condicion')),
                ('Id_Centro_Poblado', models.CharField(blank=True, max_length=10, null=True, verbose_name='Id_Centro_Poblado')),
                ('Fecha_Ultima_Regla', models.DateField(blank=True, null=True, verbose_name='Fecha_Ultima_Regla')),
                ('Fecha_Solicitud_Hb', models.DateField(blank=True, null=True, verbose_name='Fecha_Solicitud_Hb')),
                ('Fecha_Resultado_Hb', models.DateField(blank=True, null=True, verbose_name='Fecha_Resultado_Hb')),
                ('Fecha_Registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha_Registro')),
                ('Fecha_Modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha_Modificacion')),
                ('Id_Pais', models.CharField(blank=True, max_length=3, null=True, verbose_name='Id_Pais')),
            ],
        ),
    ]
